export const projects = [
  {
    title: 'Business Web - Blog',
    description: "This site is build with wordpress using elementor pro, the main goal of the site is to generate leads for a digital agency",
    long_desc: "This is my business website where I practice SEO so the website has a better ranking in Google Search Results. Nowadays it's really important to have an online presence and that’s where you have to do SEO and SEM if you want to stand out.<salto>I developed using Wordpress because if you have a blog it's easier to do SEO since there are a lot of tools to automate most of the task and you focus only on creating content to engage potential buyers.<salto>The biggest challenge was to make this site have a serious look with modern design and target the right customer for our service since I wanted to help small businesses who want to get an online presence.<salto>You might be wondering why I need more than one site ? It's because I want to have a strong personal brand but also I want to have a business brand so people know me and know my business and it helps me to land better job offers and projects.",
    image: '/images/ingenio.png',
    tags: ['Wordpress','PHP'],
    source: '/project?=businessweb',
    visit: 'https://ingeniodigitalmexico.com',
    id: 0,
  },
  {
    title: 'E-Commerce & Marketplace',
    description:"This site was custome made using Wordpress and WooCommerce, the client requested alot of custom functions for the marketplace and a offline payment for products and online payments for memberships",
    long_desc: "This is one of the bigest projects I have done so far, because it needed a lot of custom code in wordpress, I customized alot of plugins, added functions and even made a payment plugin to make the site as the client wished.<salto>The client wanted a marketplace for local stores/shops to offer their services and products online with the option to pick them up. The main goal of the web site is to be used by people who is new to online shopping or doesn´t own a credit/debit card so the interfacer was as simpler as possible and payment is mostly offline(direct deposits or cash).<salto>The bigest problem in the project was to integrate offline payments becuase every store has their own payment info and then make individual reports, Most ther plugins for ecommerce focus on online payments so there are not a lot of plugins so I had to develope a custom solution and integrated with wordpress/WooCommerce and then transalated all plugins to spanish even admin panel. Then I made a custom admin panel so people that admin the site had limited options so the site couldn't be broken by mistake.<salto>    I had to modify a lot of existing plugins in order to make add or remove options, for example to make an admin for all vendors to give them support or resolve any issue with the config and editor for some parts of the site like colors or add blocks. What I I like about all the little changes I had to do for this client, I learnt how to interact with wordpress core api.",
    image: '/images/market.png',
    tags: ['Wordpress', 'JavaScript', 'PHP'],
    source: '/project?=marketplace',
    visit: 'https://sinaloamarket.com',
    id: 1,
  },
  {
    title: 'Multiplataform APP',
    description: "This app was build using React Native to work with android and IOS at the same time. This app was able to find the closest workshop and autoparts store closes to you",
    long_desc: "the client wanted an app to locate the nearest carshop or autoparts store so the users can get help or know where to get help. The greatest challange was to make a crossplataform app with the same looks and feel for android and IOS within a month.<salto>I build the whole solution stack, web api for login and fetch data from the database as well the database used to the stores. I develope app using React Native to speed up the proccess due the time to deliver the app. one of the main problems was to render in the map all the markers and update them as the locations change without drain the battery of the user, we have to optimize this groping the map markets in clusters.<salto>The color and the UI was simple and intuitive. The client didn´t provide any guide for the design or colors palette so I focus in make the app as simple as posible becuase it was intended to be used in case of something went wrong and you need assistance with your car.<salto>the app is not realease to the public yet so I cnat upload alot of img or media or disclose more details about it, but I can say I'm glad to have worked in this project becuase It was my first international Mobile project since the company I developed this app is from USA.",
    image: '/images/app.png',
    tags: ['React Native', 'JavaScript', 'PHP'],
    source: '/project?=multiplataform_app',
    visit: '',
    id: 2,
  },
  {
    title: 'E-Commerce',
    description: "This website was build with Wordpress for the client to admin without any tech skills and have a fully customized product",
    long_desc: "The first thing I ask a client who wants a Ecommerce website it's how much visit and customers do you expect to have so I can provide a good solution. In this case they wanted a web site to sell only in México and they wanted a custom solution so I suggested to start with WooCommerce since the have physical stores around the country and they wanted a very specifict fetures that no templated basesd store would provide.<salto>I usually recomend for new business to use Shopify to help them with the logistics and Payment Gateways since it\'s expencive to certify a custom solutions to comply with PCI DSS. I usually recomned get Stripe, Paypal and OnePay for Mexican projects.<salto>The gretest challange in this project wast to implement a graphic product customization section to see the change on colors and material of the products so you could see how the product will look like and get it custome made for you. I acomplished that using js vanilla on top Wordpress Api to integrate it to WooCommerce.",
    image: '/images/ecommerce.png',
    tags: ['JavaScript', 'Wordpress', 'PHP'],
    source: '/project?=ecommerce',
    visit: '',
    id: 3,
  },
  {
    title: 'Inventory Managmenet System',
    description: "This system was integrated with a Ecommerce website to manage raw materials stocks",
    long_desc: "This was my first IT solution for a SME [Small Med-size Enterprises] and I have 4 months to develop a solution to connect inventory management with the E Commerce so the website has live inventory data and as orders are made we update the stock to automate re-orders for raw materials and make reports about sales and waste so it calculates profit.<salto>The biggest challenge was to identify the needs of the client and then make a web app. This is a critical step because in my experience as a consultant, the client does not always understand what they really need so you have to understand the business and what the client tells you they need so you can suggest a real solution for their problems.<salto>In this case it was something similar. The client wanted a cloud solution but they also wanted to host their servers, but they didn't have any IT department so this was confusing. I explained why it was best to use cloud servers and maybe in the future migrate to host their own servers. Since they are a small business the cost of servers and personnel to manage them was really expensive and it went out of budget.<salto>So I suggested a Cloud service like AWS or Google Cloud since the first year was almost free of charge and then they could evaluate if they keep it that way or start hiring an IT department, at the end the client went for the cloud service.",
    image: '/images/inventory.png',
    tags: ['JavaScript', 'Wordpress', 'PHP'],
    source: '/project?=inventory',
    visit: '',
    id: 4,
  },
  {
    title: 'Voting System',
    description: "This system to vote for candidates and track votations results live",
    long_desc: "The client for this project needed a solution to keep track of the votation in a hurry. I had 48 hrs to provide a solution. Usually I don't work like this but the payment was good enough to make an exception because it was on the weekend and the client needed the system up and running on Monday morning.<salto>In this case I didn't put much details on design or color because I was worried about the backend and to display live data as clearly as possible since the final user is people with low technical skills close to none.<salto>The system was going to be used in multiple locations and had to show real time results from all the locations in graphs and also prevent people from abuse the system to vote more than one time or alter the results since the votation was offline and people have physical access to the computer I had to obfuscate the code so people can't access critical data as easy and restrict what a user can do in the system.<salto>After all that I mounted the software and showed the cliente how to install it and use it so he could replicate the process in the other locations. Everything went well and they keep the software for future events.",
    image: '/images/votos.png',
    tags: ['JavaScript', 'Bootstrap', 'PHP'],
    source: '/project?=voting',
    visit: '',
    id: 5,
  },
  {
    title: 'Web3 site',
    description: "This site site integrate a custom api to show data from stake pools and mining pools",
    long_desc: "This was one of the biggest challenges I have faced so far, since it required me to develop an api to connect to several Blockchain nodes to wordpress so I developed a custom plugin to consolidate all the custom code and make it easy to maintain.<salto>I learned a lot about new blockchain protocols like WAVES for example which was the most demanding in customization because it required a dynamic table with live data from the blockchain, so people can look up rewards from staking and payments received from the pool.<ssalto>In every project the resources are limited so one of the challenges was to optimize the api calls, so I decided to use cache responses and reuse elements to make sure even when there is an overload in the blockchain or website there is always data to display.<salto>I went with Wordpress for this project as I have experience working with this CSM and most clients can update the content without coding skills and you can run the website in any hosting and you can customize everything to make it even easier for the clients to manipulate the site.",
    image: '/images/web3.png',
    tags: ['JavaScript', 'Wordpress', 'PHP'],
    source: '/project?=web3',
    visit: 'https://sargatxet.cloud/',
    id: 6,
  },
  {
    title: 'SargaPay Plugin',
    description: "This is a Payment Gateway to accept crypto in Wordpress Woocommerce",
    long_desc: "This plugin started as a personal project but after @Criptomonedastv made a hackathon to make a wordpress plugin to accept payments using Cardano ADA, I participated and won. So now I’m the tech lead of the project.<salto>I had a 2 months to develop a functional plugin, the greatest challenge was to use unic payment addresses derived from the same private public key (xpub) since cardano is pretty nre there were at the time a few documentation and few libraries for this propose and most of the were in haskell.<salto>I got in touch with @SebastienGllmt via twitter since he was one of the biggest developers I found in Cardano and replied to me, and he helped me to understand the process to derive and where to find the documentation about address derivation and Cardano serialization library compiled to js.<salto>So after all the research was finished, I just had one goal, to develop the wordpress plugin. I went to Platzi to find the boilerplate code for a plugin and with WooCommerce documentation, I was able to deliver on time.",
    image: '/images/sargapay.png',
    tags: ['JavaScript', 'Wordpress', 'PHP'],
    source: '/project?=sargapay',
    visit: 'https://sargatxet.cloud/sargapay-cardano/',
    id: 7,
  },
];

export const TimeLineData = [
  { year: 2012, text: 'I changed my carrer path and started my journey', },
  { year: 2014, text: 'Worked as a freelance developer', },
  { year: 2016, text: 'Started my Digital Agency', },
  { year: 2021, text: 'Started Development in web3 and open sorce', },
  { year: 2022, text: 'Looking for a job or project :D', },
];