export const projects = [
  {
    title: 'Business Web - Blog',
    description: "This site is build with wordpress using elementor pro, the main goal of the site is to generate leads for a digital agency",
      image: '/images/ingenio.png',
      tags: ['Wordpress','PHP'],
    source: 'https://google.com',
    visit: 'https://ingeniodigitalmexico.com',
    id: 0,
  },
  {
    title: 'E-Commerce & Markketplace',
    description:"This site was custome made using Wordpress and WooCommerce, the client requested alot of custom functions for the marketplace and a offline payment for products and online payments for memberships",
    image: '/images/market.png',
    tags: ['Wordpress', 'JavaScript', 'PHP'],
    source: 'https://google.com',
    visit: 'https://sinaloamarket.com',
    id: 1,
  },
  {
    title: 'Multiplataform APP',
    description: "This app was build using React Native to work with android and IOS at the same time. This app was able to find the closest workshop and autoparts store closes to you",
      image: '/images/app.png',
      tags: ['React Native', 'JavaScript', 'PHP'],
    source: '#',
    visit: '#',
    id: 2,
  },
  {
    title: 'E-Commerce',
    description: "This website was build with Wordpress for the client to admin without any tech skills and have a fully customized product",
    image: '/images/ecommerce.png',
    tags: ['JavaScript', 'Wordpress', 'PHP'],
    source: '#',
    visit: '#',
    id: 3,
  },
  {
    title: 'Inventory Managmenet System',
    description: "This system was integrated with a Ecommerce website to manage raw materials stocks",
    image: '/images/inventory.png',
    tags: ['JavaScript', 'Wordpress', 'PHP'],
    source: '#',
    visit: '#',
    id: 4,
  },
  {
    title: 'Voting System',
    description: "This system to vote for candidates and track votations results live",
    image: '/images/votos.png',
    tags: ['JavaScript', 'Bootstrap', 'PHP'],
    source: '#',
    visit: '#',
    id: 5,
  },
  {
    title: 'Web3 site',
    description: "This site site integrate a custom api to show data from stake pools and mining pools",
    image: '/images/web3.png',
    tags: ['JavaScript', 'Wordpress', 'PHP'],
    source: '#',
    visit: '#',
    id: 6,
  },
  {
    title: 'SargaPay Plugin',
    description: "This is a Payment Gateway to accept crypto in Wordpress Woocommerce",
    image: '/images/sargapay.png',
    tags: ['JavaScript', 'Wordpress', 'PHP'],
    source: '#',
    visit: '#',
    id: 7,
  },
];

export const TimeLineData = [
  { year: 2012, text: 'I changed my carrer path and started my journey', },
  { year: 2014, text: 'Worked as a freelance developer', },
  { year: 2016, text: 'Started my Digital Agency', },
  { year: 2021, text: 'Started Development in web3 and open sorce', },
  { year: 2022, text: 'Looking for a job or project :D', },
];